name: Apply Translations

on:
  push:
    branches:
      - main
    paths:
      - "weblate/**"
  workflow_dispatch:

jobs:
  apply-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3"

      - name: Run apply_translate.py
        run: python apply_translate.py

      - name: Upload target directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: translated-files
          path: target/
